apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: {{ .Release.Name }}-registry-cert
spec:
    dnsNames:
        - {{ .Values.ingress.registry.host }}
    secretName: {{ .Release.Name }}-registry-tls
    issuerRef:
        kind: ClusterIssuer
        name: {{ .Values.ingress.issuer }}
    renewBefore: 360h
    duration: 2160h
