apiVersion: v1
kind: Service
metadata:
    name: gitlabce-svc
spec:
    type: NodePort
    selector:
        app: gitlab
    ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 80
        - name: https
          protocol: TCP
          port: 443
          targetPort: 443
        - name: registry
          protocol: TCP
          port: 5678
          targetPort: 5678
