apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-n8n-svc
spec:
    type: NodePort
    selector:
        app: {{ .Release.Name }}-n8n
    ports:
        - name: http
          protocol: TCP
          port: 5678
          targetPort: 5678