#==============================================================================
# Gitlab
#==============================================================================

#==============================================================================
# Ingress
#==============================================================================
ingress:
  gitlab:
    host: git.exemple.com
  registry:
    host: registry.git.exemple.com
  issuer: letsencrypt-prod