#==============================================================================
# Gitlab
#==============================================================================

#==============================================================================
# Ingress
#==============================================================================
ingress:
  gitlab:
    host: git.exemple.com
  registry:
    host: registry.git.exemple.com
  issuer: letsencrypt-prod

# ---------------------------------------------------------------------------- #
#                                   Replicas                                   #
# ---------------------------------------------------------------------------- #
replicas:
  gitlab-runner:
    version: latest
    replicas: 2
  gitlab:
    version: latest
    replicas: 1
    storageClass:
      etc:
        name: longhorn-2-replicas
        size: 1Gi
      log:
        name: longhorn-2-replicas
        size: 1Gi
      data:
        name: longhorn-single
        size: 200Gi

# ---------------------------------------------------------------------------- #
#                                    Metier                                    #
# ---------------------------------------------------------------------------- #
gitlab-runner:
  serverToken: "xxxxxxxxxxxxxxxxxxxx"
  dockerImage: "docker:20.10.16"
  # tagList: "docker"
