#==============================================================================
# Pods
#==============================================================================

pinry:
  image: getpinry/pinry
  tag: 2.1.12
  replicaCount: 1

#==============================================================================
# Ingress
#==============================================================================
ingress:
  host: isokono.promonni.com
  issuer: letsencrypt-staging

#==============================================================================
# Métier
#==============================================================================
discord:
  bot:
    id: ""
    key: ""
    token: ""
  roleAdmin: "Le sablier"
  serverName: "Isokono"
