
#==============================================================================
# Pods
#==============================================================================
mysql:
  image: mysql
  tag: 5.6
  replicaCount: 1

bot: 
  image: monnierant/isokono-discord-bot
  tag: latest
  replicaCount: 1

api:
  image: monnierant/isokono-api-backend
  tag: latest
  replicaCount: 2

web:
  image: monnierant/isokono-website-frontend
  tag: latest
  replicaCount: 2

#==============================================================================
# Ingress
#==============================================================================
ingress:
  host: isokono.promonni.com
  issuer: letsencrypt-staging

#==============================================================================
# Métier
#==============================================================================
discord:
  bot:
    id: ""
    key: ""
    token: ""
  roleAdmin: 'Le sablier'

#==============================================================================
# Secrets
#==============================================================================
secrets:
  mysql: ""
  jwt: ""