apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-cert
spec:
  dnsNames:
    - {{ .Values.ingress.host }}
  secretName: {{ .Release.Name }}-tls
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.ingress.issuer }}