apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-mysql-secret
type: kubernetes.io/basic-auth
stringData:
    password: "{{ .Values.secrets.mysql }}"
immutable: true
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-discord-secret
type: Opaque
stringData:
    id: "{{ .Values.discord.bot.id }}"
    key: "{{ .Values.discord.bot.key }}"
    bot-token: "{{ .Values.discord.bot.token }}"
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-jwt-secret
type: Opaque
stringData:
    secret: "{{ .Values.secrets.jwt }}"
---
