apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-svc
  namespace: {{ .Release.Name }}-main
spec:
  selector:
    app: {{ .Release.Name }}-web
  ports:
    - port: 80
      targetPort: 4200